"""inject_scheduler.py — Injects run_paparazzi_cycle + dispatcher into actress_scheduler.py"""
import os

path = os.path.join(os.path.dirname(__file__), "..", "Actress_Modules", "actress_scheduler.py")

with open(path, "rb") as f:
    raw = f.read()

lines = raw.decode("utf-8").split("\r\n")
print(f"Total lines: {len(lines)}")

# Lines 698-851 (0-indexed) are run_daily_cycle — replace with dispatcher + classic + paparazzi

NEW_CODE = [
    "def run_daily_cycle() -> None:",
    '    """',
    "    Dispatcher for harvest cycles.",
    "    PAPARAZZI_MODE=yes in Credentials/.env -> run_paparazzi_cycle() (gender routing).",
    "    Otherwise -> classic actress-account mode (backward compatible).",
    '    """',
    "    import re as _re, os as _os",
    '    _env_path = _os.path.join(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))), "Credentials", ".env")',
    "    _paparazzi_mode = False",
    "    try:",
    '        with open(_env_path, "r", encoding="utf-8", errors="ignore") as _f:',
    "            _txt = _f.read()",
    '        _m = _re.search(r"(?m)^PAPARAZZI_MODE=(.+)$", _txt)',
    '        if _m and _m.group(1).strip().lower() in ("yes", "true", "1"):',
    "            _paparazzi_mode = True",
    "    except Exception:",
    "        pass",
    "",
    "    if _paparazzi_mode:",
    "        run_paparazzi_cycle()",
    "    else:",
    "        _run_classic_cycle()",
    "",
    "",
    "def _run_classic_cycle() -> None:",
    '    """Classic actress-account mode (legacy). Reads from actress_accounts.json."""',
    "    from Actress_Modules.actress_config import (",
    "        get_all_active_accounts,",
    "        run_monthly_rescan,",
    "        is_account_mode_enabled,",
    "    )",
    "",
    "    if not is_account_mode_enabled():",
    '        logger.info("Account Mode OFF - skipping classic cycle")',
    "        return",
    "",
    "    if not _today_is_scheduled():",
    '        logger.info("Today not in ACTRESS_RUN_DAYS - skipping")',
    "        return",
    "",
    '    logger.info("=" * 60)',
    '    logger.info("AMTCE CLASSIC SCHEDULER - Daily Cycle Starting")',
    '    logger.info("Time: %s", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))',
    '    logger.info("=" * 60)',
    "",
    "    run_monthly_rescan()",
    "",
    "    from Download_Modules.apify_downloader import apify_scrape_actress_accounts",
    "    from Download_Modules.downloader       import download_video",
    "    from Actress_Modules.actress_ledger    import get_ledger, extract_shortcode",
    "",
    "    accounts = get_all_active_accounts()",
    "    ledger   = get_ledger()",
    "",
    "    all_usernames = [username for username, _, _ in accounts]",
    '    logger.info("Fetching ALL %d accounts in ONE Apify call ...", len(all_usernames))',
    "",
    "    all_reels = apify_scrape_actress_accounts(",
    '        actress_name      = "batch",',
    "        source_accounts   = all_usernames,",
    "        limit_per_account = LIMIT_PER_ACCOUNT,",
    "    )",
    "",
    "    if not all_reels:",
    '        logger.warning("Apify returned no reels.")',
    "        return",
    "",
    "    account_map = {",
    '        username.lstrip("@"): (folder, title)',
    "        for username, folder, title in accounts",
    "    }",
    "",
    "    from collections import defaultdict",
    "    reels_by_account: dict = defaultdict(list)",
    "    for reel in all_reels:",
    '        owner = reel.get("ownerUsername", "").lstrip("@").lower()',
    "        reels_by_account[owner].append(reel)",
    "",
    "    total_dl      = 0",
    "    total_skipped = 0",
    '    downloads_dir = os.getenv("DOWNLOADS_DIR", "downloads")',
    "",
    "    for username_raw, folder_title in account_map.items():",
    "        username       = username_raw.lower()",
    "        actress_folder, actress_title = folder_title",
    "        reels          = reels_by_account.get(username, [])",
    "",
    "        if not reels:",
    "            continue",
    "",
    "        batch_folder = _next_batch_folder(actress_title, downloads_dir)",
    "        downloaded = 0",
    "        for reel in reels:",
    "            if downloaded >= DOWNLOADS_PER_ACCOUNT:",
    "                break",
    "",
    '            video_url = reel.get("videoUrl", "")',
    "            if not video_url:",
    "                continue",
    "",
    "            if not _name_in_reel(reel, actress_folder):",
    "                continue",
    "",
    '            shortcode = reel.get("shortcode")',
    "            if not shortcode:",
    '                post_url  = reel.get("url") or reel.get("postUrl") or video_url',
    "                shortcode = extract_shortcode(post_url)",
    "",
    "            if shortcode and ledger.shortcode_seen(shortcode):",
    "                continue",
    "",
    '            os.environ["SKIP_AUDIO_EXTRACT"] = "true"',
    "            video_path, _ = download_video(video_url)",
    '            os.environ.pop("SKIP_AUDIO_EXTRACT", None)',
    "",
    "            if not video_path:",
    "                continue",
    "",
    "            if ledger.hash_seen(video_path):",
    "                if shortcode:",
    "                    ledger.commit(shortcode, video_path)",
    "                try:",
    "                    os.remove(video_path)",
    "                except Exception:",
    "                    pass",
    "                continue",
    "",
    "            video_path = _organize_clip(video_path, actress_title, batch_folder, downloaded + 1)",
    "            _inject_niche(video_path, actress_folder, actress_title)",
    "            ledger.commit(shortcode, video_path)",
    "            downloaded += 1",
    "            total_dl   += 1",
    "            PublishQueue.add(video_path, actress_title, actress_folder)",
    "",
    "        total_skipped += (LIMIT_PER_ACCOUNT - downloaded)",
    "",
    '    logger.info("Classic cycle complete: %d downloaded, %d skipped", total_dl, total_skipped)',
    "",
    "",
    "def run_paparazzi_cycle() -> None:",
    '    """',
    "    NEW Paparazzi Channel Harvest Cycle (PAPARAZZI_MODE=yes in .env).",
    "    Scrapes paparazzi source accounts from paparazzi_identities.json.",
    "    Resolves gender/identity via channel_router:",
    "      - Women identified  -> General_Fallback",
    "      - Men / Unknown     -> Paparazzi_Channel",
    "    Cross-channel dedup: same clip NEVER appears on 2 channels.",
    '    """',
    "    from Actress_Modules.actress_config import is_account_mode_enabled",
    "    from Actress_Modules.channel_router import (",
    "        get_source_accounts,",
    "        resolve_channel,",
    "        CHANNEL_WOMEN,",
    "        CHANNEL_ALL,",
    "    )",
    "",
    "    if not is_account_mode_enabled():",
    '        logger.info("AAS OFF - skipping paparazzi cycle")',
    "        return",
    "",
    "    if not _today_is_scheduled():",
    '        logger.info("Today not in ACTRESS_RUN_DAYS - skipping")',
    "        return",
    "",
    '    logger.info("=" * 60)',
    '    logger.info("AMTCE PAPARAZZI SCHEDULER - Harvest Cycle Starting")',
    '    logger.info("%s", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))',
    '    logger.info("=" * 60)',
    "",
    "    from Download_Modules.apify_downloader import apify_scrape_actress_accounts",
    "    from Download_Modules.downloader       import download_video",
    "    from Actress_Modules.actress_ledger    import get_ledger, extract_shortcode",
    "",
    "    source_accounts = get_source_accounts()",
    "    if not source_accounts:",
    '        logger.error("No source accounts in paparazzi_identities.json. Add IG IDs and restart.")',
    "        return",
    "",
    "    ledger = get_ledger()",
    '    logger.info("Fetching %d paparazzi source accounts via Apify...", len(source_accounts))',
    "",
    "    all_reels = apify_scrape_actress_accounts(",
    '        actress_name      = "paparazzi",',
    "        source_accounts   = source_accounts,",
    "        limit_per_account = LIMIT_PER_ACCOUNT,",
    "    )",
    "",
    "    if not all_reels:",
    '        logger.warning("Apify returned no reels for this harvest cycle.")',
    "        return",
    "",
    '    logger.info("Total reels from Apify (post-filter): %d", len(all_reels))',
    "",
    '    downloads_dir = os.getenv("DOWNLOADS_DIR", "downloads")',
    "    total_dl      = 0",
    "    total_skipped = 0",
    "    channel_counts: dict = {}",
    "",
    "    for reel in all_reels:",
    '        video_url = reel.get("videoUrl", "")',
    "        if not video_url:",
    "            continue",
    "",
    '        ig_id = reel.get("ownerUsername", "").lower()',
    "        actress_folder, actress_title, is_nsfw = resolve_channel(ig_id, reel)",
    "",
    "        ch_count = channel_counts.get(actress_folder, 0)",
    "        if ch_count >= DOWNLOADS_PER_ACCOUNT:",
    "            total_skipped += 1",
    "            continue",
    "",
    '        shortcode = reel.get("shortcode")',
    "        if not shortcode:",
    '            post_url  = reel.get("url") or reel.get("postUrl") or video_url',
    "            shortcode = extract_shortcode(post_url)",
    "",
    "        if shortcode and ledger.shortcode_seen(shortcode):",
    '            logger.info("[L1] Shortcode %s already downloaded - skipping", shortcode)',
    "            total_skipped += 1",
    "            continue",
    "",
    "        if shortcode:",
    "            existing_ch = ledger.channel_for_shortcode(shortcode)",
    "            if existing_ch and existing_ch != actress_folder:",
    '                logger.info("[CROSS-DEDUP] %s used by %s - skip for %s",',
    "                            shortcode, existing_ch, actress_folder)",
    "                total_skipped += 1",
    "                continue",
    "",
    '        logger.info("Downloading: @%s -> %s (%s)%s",',
    '                    ig_id, actress_folder, actress_title, " [NSFW]" if is_nsfw else "")',
    "",
    '        os.environ["SKIP_AUDIO_EXTRACT"] = "true"',
    "        video_path, _ = download_video(video_url)",
    '        os.environ.pop("SKIP_AUDIO_EXTRACT", None)',
    "",
    "        if not video_path:",
    '            logger.warning("Download failed: %s", video_url[:80])',
    "            continue",
    "",
    "        if ledger.hash_seen(video_path):",
    "            if shortcode:",
    "                ledger.commit_with_channel(shortcode, video_path, actress_folder)",
    "            try:",
    "                os.remove(video_path)",
    "            except Exception:",
    "                pass",
    "            continue",
    "",
    '        safe_ch   = actress_folder.replace(" ", "_")',
    "        safe_name = _safe_title(actress_title)",
    '        batch_folder = _next_batch_folder("%s_%s" % (safe_ch, safe_name), downloads_dir)',
    "        clip_idx  = ch_count + 1",
    "",
    "        video_path = _organize_clip(",
    "            video_path,",
    '            "%s - %s" % (actress_folder, actress_title),',
    "            batch_folder,",
    "            clip_idx,",
    "        )",
    "        _inject_niche(video_path, actress_folder, actress_title)",
    "        ledger.commit_with_channel(shortcode, video_path, actress_folder)",
    "",
    "        channel_counts[actress_folder] = ch_count + 1",
    "        total_dl += 1",
    "        PublishQueue.add(video_path, actress_title, actress_folder)",
    "",
    '    logger.info("=" * 60)',
    '    logger.info("Paparazzi cycle complete: %d downloaded | %d skipped", total_dl, total_skipped)',
    "    for ch, cnt in channel_counts.items():",
    '        logger.info("  %s: %d clip(s)", ch, cnt)',
    '    logger.info("=" * 60)',
]

new_lines = lines[:698] + NEW_CODE + lines[852:]
new_content = "\r\n".join(new_lines)

with open(path, "wb") as f:
    f.write(new_content.encode("utf-8"))

print(f"Done. New file: {len(new_lines)} lines")
